### ISSUE TITLE
basis_get_target_location incorrect for shared library

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#448]
there is an if statement that checks for "STATIC" it should also check for "SHARED_LIBRARY"

**Comment by schuhschuh** [comment]
That's not correct. It wasn't missing. The first if checks whether the target is a library. The second if-else is to deal with static an shared libraries separately. If it is not a static library, the else branch is used, i.e., the else branch is for "SHARED_LIBRARY", "MODULE", and "MEX" targets. The if branch is only valid for "STATIC_LIBRARY". A shared library should not have an "archive". This term is only used for static libraries.

Please revert commit c8de650.

Can you elaborate on your particular setup/issue you encountered that you thought this change was necessary so we can find the appropriate solution?

**Comment by schuhschuh** [comment]
It's possible you were interested in the import library of a DLL on Windows. These are ARCHIVE's for CMake: http://www.cmake.org/cmake/help/v3.3/manual/cmake-buildsystem.7.html#archive-output-artifacts

Maybe we need an option which will return you the path of the .lib import library instead of the .dll on Windows.

**Comment by ahundt** [comment]
Oh sorry about that if it was incorrect. I made the change a while ago on
my tree so I don't remember the reason. Sorry but I'm traveling at the
moment so I can't revert it until next week.

On Wednesday, August 12, 2015, Andreas Schuh <notifications@github.com>
wrote:

> That's not correct. It wasn't missing. The first if checks whether the
> target is a library. The second if-else is to deal with static an shared
> libraries separately. If it is not a static library, the else branch is
> used, i.e., the else branch is for "SHARED_LIBRARY", "MODULE", and "MEX"
> targets. The if branch is only valid for "STATIC_LIBRARY". A shared library
> should not have an "archive". This term is only used for static libraries.
>
> Please revert commit c8de650
> <https://github.com/schuhschuh/cmake-basis/commit/c8de65065fe243b9d03dab8e40f230dc0d6abc87>
> .
>
> Can you elaborate on your particular setup/issue you encountered that you
> thought this change was necessary so we can find the appropriate solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schuhschuh/cmake-basis/issues/448#issuecomment-130255408>
> .
>


-- 

Cheers!
Andrew Hundt

**Comment by schuhschuh** [comment]
No worries, there's no rush.

**Comment by ahundt** [comment]
change undone

**Comment by schuhschuh** [comment]
Shall we rename this issue to "Add basis_get_target_link_library function" as suggested in my previous comment ? Was that the feature you were looking for ? Otherwise, this bug report seems to be invalid and can be closed unless you provide some more specifics as to why you needed this change before.

**Comment by ahundt** [comment]
I'm using OS X at the moment. I think this can be closed unless a problem is reported again then we can reopen or go into more detail.
