### ISSUE TITLE
When will version 3.2.0 be released ?

### ISSUE THREAD

**Issue by jkhoogland** [schuhschuh/cmake-basis#451]
Hi,
I noticed that the last release was made in March 2014,
what is the timeline for the next release ?
Regards
Jiri

**Comment by schuhschuh** [comment]
Hi Jiri,

you are right, the release cycles have become extremely long and a new release is more than appropriate at this point given that CMake 3.x is used by most developers. This also relates to Andrew's earlier suggestion #447.

Most of the 3.1.1 milestone issues were just left alone in testing stage which I never got around to complete. But I'd say we can skip a rigour testing and accept the changes as they are. Non-completed issues can be postponed.

I will target a new release by the end of the month.

Best,
Andreas

**Comment by ahundt** [comment]
Thanks for improving so many things again @schuhschuh! Do you think you could go through the release steps for a reasonable subset of what is already done? That would help with writing a homebrew script and a few other things so it isn't necessary to keep using the develop branch!

**Comment by schuhschuh** [comment]
There are only few open issues which don't require much effort that I wanted to include as well:

- [ ] #395 Build shared MATLAB Compiler libraries for C++ (BASIS doesn't support plain C)
- [ ] #426 Should be fixed by now, actually
- [ ] #486
- [ ] #487

Testing of bootstrapping:
- [ ] #408 
- [ ] #414

Testing of BASIS_BUILD_ONLY, is BASISConfig.cmake generated now?
- [ ] #411

Have you seen my comments on the Homebrew issue #450 ? I thought if it was done prior to the release, it could be mentioned in the documentation. I think you could finalize the script even before the actual release version is tagged and add the corresponding installation steps to the BASIS installation instructions for OS X.

**Comment by schuhschuh** [comment]
All issues for the next release are now finished.
