### ISSUE TITLE
Document how to create betas and releases (for user projects) with basis

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#470]
There should be something explaining how to make a release vs beta, including source and pdf, and a . I don't really know how that works. Also, perhaps add a way to include the exact date and time when the release pdf is generated similarly to what is included in the beta pdfs.

Originally mentioned in #399

**Comment by schuhschuh** [comment]
The differentiation between beta and release is done by either setting a valid project version (format major.minor.patch) for a release or using "0.0.0" as VERSION for beta / development branches / builds. This info is a bit hidden in the (outdated) [Branch and Release](http://opensource.andreasschuh.com/cmake-basis/howto/branch-and-release.html#releasing-software) guide. An explanation could be added to the [Configure a Project](http://opensource.andreasschuh.com/cmake-basis/howto/configure-project.html#basisproject-cmake) how-to guide.

How to generate the manual and/or web pages is explained in the general [build instructions](http://opensource.andreasschuh.com/cmake-basis/howto/install.html#build-the-software) and you also added a brief section to [in this how-to guide](http://opensource.andreasschuh.com/cmake-basis/howto/document.html#generating-documentation).

Not clear about the timestamp request. I wouldn't include the time itself, the date should be sufficient which is included already:
<img width="681" alt="screen shot 2015-09-14 at 17 02 05" src="https://cloud.githubusercontent.com/assets/975451/9854774/6d1fac50-5b02-11e5-8180-038bbf5e42be.png">
The only difference here when VERSION is "0.0.0" is that instead of the version number underneath the title, you get either the SVN revision number, Git HEAD SHA1, or a build time stamp made up of the date only ("bYYYYMMDD"). The date below the author line is present in both cases.

**Comment by ahundt** [comment]
Cool, perhaps the info should be consolidated somewhere in the docs with a heading to make it easy to find?
